version: '3.6'
services:
  database:
    image: "postgres"
    environment:
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpassword"
      POSTGRES_DB: "justcommerce"
      PGDATA: /data/postgres
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge